---
title: "R-Club 05-31"
output: 
  html_document: 
    keep_md: yes
---

```{r}
library(tidyverse)
as_tibble(iris)

tibble(
  x = 1:5, 
  y = 1, 
  z = x ^ 2 + y
)

tb <- tibble(
  `:)` = "smile", 
  ` ` = "space",
  `2000` = "number"
)
tb

tibble(
  a = lubridate::now() + runif(1e3) * 86400,
  b = lubridate::today() + runif(1e3) * 30,
  c = 1:1e3,
  d = runif(1e3),
  e = sample(letters, 1e3, replace = TRUE)
)

nycflights13::flights %>% 
  print(n = 10, width = Inf)

nycflights13::flights %>% 
  View()

df <- tibble(
  x = runif(5),
  y = rnorm(5)
)

df$x
df[["x"]]
class(as.data.frame(tb))

```

```{r}
#Exercise 1

print(mtcars)
#The tibble will only present the 10 rows, but when printed with dataframe will show the whole dataframe.

#Exercise 2

df <- data.frame(abc = 1, xyz = "a")

#with the dataframe
df$x
df[, "xyz"]
df[, c("abc", "xyz")]

#with the tibble 
df_tb <- as_tibble(df)
df_tb$x
df_tb[, "xyz"]
df_tb[, c("abc", "xyz")]

#When using with tibble, $x cannot be recognized

#Exercise 3
mtcars_tb <- as_tibble(mtcars)
var <- "mpg"
mtcars_tb[[var]]

#Exercise 4

annoying <- tibble(
  `1` = 1:10,
  `2` = `1` * 2 + rnorm(length(`1`))
)

annoying[[1]]

ggplot(annoying, aes(`1`, `2`)) +
  geom_point()

annoying_plus <- mutate(annoying, `3` = `2` / `1`)

annoying_plus_names <- rename(annoying_plus, One = `1`, Two = `2`, Three = `3`)

#Exercise 5
tibble::enframe(1:10)
#It includes a serial number column on the left.

#Exercise 6 
# with help on searching that, it is "tibble.max_extra_cols"
```

